from datetime import date
import os
from typing import Optional
from fastapi import FastAPI
from sqlmodel import Field, Session, SQLModel, create_engine
from enum import Enum

class EngineType(str, Enum):
    SQLITE_IN_MEMORY = "sqlite_in_memory"
    SQLITE_FILE = "sqlite_file"
    DUCKDB_IN_MEMORY = "duckdb_in_memory"
    DUCKDB_FILE = "duckdb_file"

class DatabaseFactory:
    def __init__(self):
        self._engines = {}
        CUR_DIR = os.path.dirname(os.path.abspath(__file__))
        self._config = {
            EngineType.SQLITE_IN_MEMORY: "sqlite:///:memory:",
            EngineType.SQLITE_FILE: f"sqlite:///{os.path.join(CUR_DIR, 'Data', 'transaction.db').replace(os.sep, '/')}",
            EngineType.DUCKDB_IN_MEMORY: "duckdb:///:memory:",
            EngineType.DUCKDB_FILE: f"duckdb:///{os.path.join(CUR_DIR, 'Data', 'analytical.duckdb').replace(os.sep, '/')}"
        }

class ExperienceType(str, Enum):
    WORK = "work"
    VOLUNTEER = "volunteer"

# 1. Define the Model (It's a Pydantic model AND a SQL Table)
class Experience(SQLModel, table=True):
    # primary key is optional because it will be auto-generated by the database
    id: Optional[int] = Field(default=None, primary_key=True)

    # 
    type: ExperienceType = Field(index=True)
    role: Optional[str] = None
    org_name: str = Field(index=True)
    city: str
    country: str
    start_date: date
    end_date: Optional[date] = None
    is_current: bool = False
    description: Optional[str] = None

class CredentialType(str, Enum):
    PROFESSIONAL = "professional"
    COMPETITIONS = "competitions"
    PUBLICATIONS = "publications"
    PATENT = "patent"
    AWARDS = "awards"
    COURSES = "courses"

class Credential(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    name: str
    institution: str
    type: CredentialType = Field(index=True)
    date_obtained: Optional[date] = None
    date_expired: Optional[date] = None
    credential_id: Optional[str] = None
    credential_url: Optional[str] = None
    is_ongoing: bool = False

# 2. Setup DB connection
db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "Data", "database.db")
relational_url = f"sqlite:///{db_path.replace(os.sep, '/')}"
relational_engine = create_engine(relational_url)

non_relational_url = f"sqlite:///{db_path.replace(os.sep, '/')}"


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)

app = FastAPI()

# 3. Use it in a FastAPI endpoint
@app.post("/heroes/")
def create_hero(hero: Hero):
    with Session(engine) as session:
        session.add(hero)
        session.commit()
        session.refresh(hero)
        return hero