import pandera as pa
from pandera.typing import Series
from typing import Optional

class ApplicationCSVSchema(pa.DataFrameModel):
    Application_ID: Series[str] = pa.Field(str_matches=r"^APP-\d{3}$")
    Date_Applied: Series[str] = pa.Field(nullable=False)
    Company: Series[str] = pa.Field(nullable=False)
    Role_Title: Series[str] = pa.Field(nullable=False)
    Role_Type: Series[str] = pa.Field(nullable=True)
    Sector: Series[str] = pa.Field(nullable=True)
    Source: Series[str] = pa.Field(nullable=True)
    Salary_Min: Series[float] = pa.Field(nullable=True)
    Salary_Max: Series[float] = pa.Field(nullable=True)
    Location: Series[str] = pa.Field(nullable=True)
    Work_Mode: Series[str] = pa.Field(isin=["Remote", "Hybrid", "On-site"])
    Status: Series[str] = pa.Field(isin=["Applied", "Screening", "Interview", "Offer", "Rejected", "Stalled"])
    Recruiter_Name: Series[str] = pa.Field(nullable=True)
    Recruiter_Contact: Series[str] = pa.Field(nullable=True)
    Next_Action: Series[str] = pa.Field(nullable=True)
    Outcome: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class InterviewLogCSVSchema(pa.DataFrameModel):
    Interview_ID: Series[str] = pa.Field(str_matches=r"^INT-\d{3}$")
    Date: Series[str] = pa.Field(nullable=False)
    Company: Series[str] = pa.Field(nullable=False)
    Role_Title: Series[str] = pa.Field(nullable=False)
    Role_Type: Series[str] = pa.Field(nullable=True)
    Round: Series[int] = pa.Field(ge=1)
    Format: Series[str] = pa.Field(nullable=True)
    Interviewer: Series[str] = pa.Field(nullable=True)
    Duration_mins: Series[float] = pa.Field(nullable=True)
    Status: Series[str] = pa.Field(nullable=True)
    Outcome: Series[str] = pa.Field(nullable=True)
    Detail_File: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class PreferredCompanyCSVSchema(pa.DataFrameModel):
    Company_ID: Series[str] = pa.Field(str_matches=r"^CO-\d{3}$")
    Company: Series[str] = pa.Field(nullable=False)
    Sector: Series[str] = pa.Field(nullable=True)
    Why_Preferred: Series[str] = pa.Field(nullable=True)
    Target_Division: Series[str] = pa.Field(nullable=True)
    Known_Roles: Series[str] = pa.Field(nullable=True)
    Website: Series[str] = pa.Field(nullable=True)
    LinkedIn: Series[str] = pa.Field(nullable=True)
    Status: Series[str] = pa.Field(nullable=True)
    Last_Checked: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class SkillInventoryCSVSchema(pa.DataFrameModel):
    Category: Series[str] = pa.Field(nullable=False)
    Skill: Series[str] = pa.Field(nullable=False)
    Proficiency: Series[float] = pa.Field(in_range={"min_value": 1.0, "max_value": 5.0})
    Years_Experience: Series[float] = pa.Field(ge=0)
    Last_Used: Series[str] = pa.Field(nullable=True)
    Evidence_Where_Used: Series[str] = pa.Field(nullable=True)
    Gap_SA: Series[str] = pa.Field(isin=["Y", "N", ""], nullable=True) 
    Gap_TPM: Series[str] = pa.Field(isin=["Y", "N", ""], nullable=True)
    Gap_TBA: Series[str] = pa.Field(isin=["Y", "N", ""], nullable=True)
    Priority_to_Improve: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class CertificationCSVSchema(pa.DataFrameModel):
    Cert_ID: Series[str] = pa.Field(str_matches=r"^CRT-\d{3}$")
    Certification_Name: Series[str] = pa.Field(nullable=False)
    Issuing_Body: Series[str] = pa.Field(nullable=True)
    Date_Obtained: Series[str] = pa.Field(nullable=True)
    Credential_ID: Series[str] = pa.Field(nullable=True)
    Status: Series[str] = pa.Field(nullable=True)
    Expiry_Renewal: Series[str] = pa.Field(nullable=True)
    URL: Series[str] = pa.Field(nullable=True)
    Relevant_Roles: Series[str] = pa.Field(nullable=True)
    Priority: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class CourseCSVSchema(pa.DataFrameModel):
    Course_ID: Series[str] = pa.Field(str_matches=r"^CRS-\d{3}$")
    Course_Name: Series[str] = pa.Field(nullable=False)
    Provider: Series[str] = pa.Field(nullable=True)
    Type: Series[str] = pa.Field(nullable=True)
    Format: Series[str] = pa.Field(nullable=True)
    Completion_Date: Series[str] = pa.Field(nullable=True)
    Status: Series[str] = pa.Field(nullable=True)
    URL: Series[str] = pa.Field(nullable=True)
    Certificate_YN: Series[str] = pa.Field(isin=["Y", "N", ""], nullable=True)
    Skills_Covered: Series[str] = pa.Field(nullable=True)
    Relevant_Roles: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class PublicationCSVSchema(pa.DataFrameModel):
    Pub_ID: Series[str] = pa.Field(str_matches=r"^PUB-\d{3}$")
    Title: Series[str] = pa.Field(nullable=False)
    Publication_Type: Series[str] = pa.Field(nullable=True)
    Publisher_Journal: Series[str] = pa.Field(nullable=True)
    Date_Published: Series[str] = pa.Field(nullable=True)
    Role: Series[str] = pa.Field(nullable=True)
    Co_Authors: Series[str] = pa.Field(nullable=True)
    URL: Series[str] = pa.Field(nullable=True)
    Paper_ID: Series[str] = pa.Field(nullable=True)
    Citations: Series[float] = pa.Field(nullable=True)
    Domain: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class ProfessionalTrackerCSVSchema(pa.DataFrameModel):
    Phase: Series[str] = pa.Field(nullable=True)
    KPI_Category: Series[str] = pa.Field(nullable=True)
    Metric_Objective: Series[str] = pa.Field(nullable=False)
    Base_State: Series[str] = pa.Field(nullable=True)
    Target_Goal: Series[str] = pa.Field(nullable=True)
    Target_Salary_Impact: Series[str] = pa.Field(nullable=True)
    Timeline_Deadline: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)

class VisaTrackerCSVSchema(pa.DataFrameModel):
    Criteria_Category: Series[str] = pa.Field(nullable=False)
    Criteria_Sub_Type: Series[str] = pa.Field(nullable=True)
    Evidence_Description: Series[str] = pa.Field(nullable=False)
    Verifier_Signatory: Series[str] = pa.Field(nullable=True)
    Artifact_Source: Series[str] = pa.Field(nullable=True)
    Status: Series[str] = pa.Field(nullable=True)
    Impact_Scale: Series[str] = pa.Field(nullable=True)
    Notes: Series[str] = pa.Field(nullable=True)
